// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3PGPKDqmTSNiG7POgvNu2KMkPvVSdX1M',
    appId: '1:632190892128:web:19032accd48b3e5507ab05',
    messagingSenderId: '632190892128',
    projectId: 'campingbazzar',
    authDomain: 'campingbazzar.firebaseapp.com',
    storageBucket: 'campingbazzar.firebasestorage.app',
    measurementId: 'G-XRCD41V4YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0ET8qJFvdPaYsCmIaxmnn4EqUy0_D0jk',
    appId: '1:632190892128:android:2871e7351a28a91f07ab05',
    messagingSenderId: '632190892128',
    projectId: 'campingbazzar',
    storageBucket: 'campingbazzar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOB4jC_Dxtmu2PatWJ01AYrd25ZFYFCkw',
    appId: '1:632190892128:ios:b9fd89ab8dab336607ab05',
    messagingSenderId: '632190892128',
    projectId: 'campingbazzar',
    storageBucket: 'campingbazzar.firebasestorage.app',
    iosClientId: '632190892128-2a2obq907e8bp8l7mo04feoji50304s5.apps.googleusercontent.com',
    iosBundleId: 'com.example.campingbazar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOB4jC_Dxtmu2PatWJ01AYrd25ZFYFCkw',
    appId: '1:632190892128:ios:b9fd89ab8dab336607ab05',
    messagingSenderId: '632190892128',
    projectId: 'campingbazzar',
    storageBucket: 'campingbazzar.firebasestorage.app',
    iosClientId: '632190892128-2a2obq907e8bp8l7mo04feoji50304s5.apps.googleusercontent.com',
    iosBundleId: 'com.example.campingbazar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3PGPKDqmTSNiG7POgvNu2KMkPvVSdX1M',
    appId: '1:632190892128:web:531aebe3143df15807ab05',
    messagingSenderId: '632190892128',
    projectId: 'campingbazzar',
    authDomain: 'campingbazzar.firebaseapp.com',
    storageBucket: 'campingbazzar.firebasestorage.app',
    measurementId: 'G-3QXD8V0VVE',
  );
}
